package com.pp.exception;

public class TestResultsNotFoundException extends RuntimeException {
public TestResultsNotFoundException(String message) {
	super(message);
}
}
